### ISSUE TITLE
lin-arm64 builds. init() not found on plugin load?

### ISSUE THREAD

**Issue by jackokring** [qno/vcv-plugin-cmake-example#3] opened 2023-01-31 12:20 UTC
I know it's not technically supported by the official library (`lin-arm64`) but I have found that the build process makes both a `plugin.so` and a `plugin-arm64.so`. So to get some plugins to "work" I had to delete `plugin-arm64.so` and rename `plugin.so` to `plugin-arm64.so` before `make dist`. That particular `.so` does load.

I was directed here by `Airwin2Rack` as it seems this is the common upstream of a number of plugins. The `plugin-arm64.so` is always smaller than the `plugin.so` after a `make dep`. I'm not quite sure how to edit the `Makefile` to avoid a manual delete and rename.

The issue is likely related to the new `mac-arm64` introduction and resultant change of architecture append naming of the dynamic libraries generated.

**Comment by jackokring** [comment] 2023-01-31 12:43
[Screenshots-as-scrolling-up-to-working-Airwin2Rack.zip](https://github.com/qno/vcv-plugin-cmake-example/files/10546421/Screenshots-as-scrolling-up-to-working-Airwin2Rack.zip) so order by decending datetime. So initial `make dist` error on load. and then work around.

**Comment by baconpaul** [comment] 2023-01-31 13:22
You want the okugin to be named -arm64 though right? So the problem here is that you are getting a plugin.so

have you tried to fix it at all?

**Comment by jackokring** [comment] 2023-01-31 13:37
Yes, it is possible to work around it as the screenshots show (order by descending date, taken scrolling up the terminal log). It is also unrelated to the patch of https://github.com/AndrewBelt/osdialog/commit/1c9aaab9aae8df296439d46bd83acbf326522ea7 applied between `Prefabs` and `Airwin2Rack` builds (update of `git submodule update --init --recursive`) so both had the issue. They also both have the segmentation fault when I closed Rack after inserting the module from a Rack `make run` debug (I think it applies the `./Rack -d` option). Open and close again is fine.

**Comment by baconpaul** [comment] 2023-01-31 13:43
I dunno I think it’s a bit unclear - is there no better bug report than a zip of screenshots? 

None of this stuff works Linux arm. What plugin.mk changes and rack changes did you make? Is the arm make variable set at build time?

**Comment by jackokring** [comment] 2023-01-31 16:10
I'm using a Rack `2.2.3` build from source (not SDK, and a minor fix for `libsamplerate-1.9`). I have made no changes to any make process except `-j 1` to stop my web browser from being useful as the build happens. `make dep`, `make dist`, bug, delete `plugin-arm64.s0`, `mv plugin.so plugin-arm64.so`, `chmod +x plugin-arm64.so`, `make dist` works with the slight (unnoticed except in the console log) of a segmentation fault on closing rack for the first time after an insert of the module (could just be how they made it).

Like I said it's a `lin-arm64` build so I'm not expecting a fix as it's not an officially supported architecture. Other people might like to know how to make such a build though.

For my own self developed plugins I'm not using CMake so I haven't a need to fix it as the work around worked enough for me.,

**Comment by jackokring** [comment] 2023-01-31 16:18
I'm maybe betting on a `C++11` vs `C++17` (maybe callback clean up) bug?

**Comment by baconpaul** [comment] 2023-01-31 16:21
Right so the system on Linux is confused for arm vs not is my bet. Until the sdk has a way to flag an arm build it will be clumsy I bet

**Comment by qno** [comment] 2023-01-31 16:53
So as this platform is not officially supported I'll not support this as well.

You can adapt your own copy if you want. 

You need to add changes in [RackSDK.cmake#L28](https://github.com/qno/vcv-plugin-cmake-example/blob/main/RackSDK.cmake#L28) to figure out that you are building for ARM64 Linux.
```
# Do not change the RACK_PLUGIN_LIB!
if (${CMAKE_OSX_ARCHITECTURES} MATCHES "arm64")
  set(RACK_PLUGIN_ARCH -arm64)
endif ()
set(RACK_PLUGIN_LIB plugin${RACK_PLUGIN_ARCH})
```
and then adapt also the [Makefile](https://github.com/qno/vcv-plugin-cmake-example/blob/main/Makefile#L7) so have to set the `RACK_PLUGIN_ARCH ` to `-arm64` when you have detected that you are builing ARM64 Linux.


The problem is that the Rack-SDK Makefile will build an `plugin-arm64.so` for Linux but the `Rack-SDK.cmake` builds a `plugin.so`. You could then also just change the [plugin.mk](https://github.com/VCVRack/Rack/blob/v2/plugin.mk#L27) and change
```
TARGET := plugin
ifndef ARCH_X64
	# On non-x64, append CPU name to plugin binary
	TARGET := $(TARGET)-$(ARCH_CPU)
endif
```
to
```
TARGET := plugin
ifndef ARCH_X64
	# On non-x64, append CPU name to plugin binary
	TARGET := $(TARGET)-$(ARCH_CPU)
endif
ifdef ARCH_LINUX
      TARGET := plugin
endif
```
So you just reset the target back to `plugin.so` as I doubt that VCVRack loads a `plugin-arm64.so` on Linux anyway.

**Comment by qno** [comment] 2023-01-31 17:16
OK - I have seen that Rack does actually load a `plugin-arm64.so` if ARM64 Linux, so you can't just hack the `plugin.mk`.
See [plugin.cpp#L112](https://github.com/VCVRack/Rack/blob/v2/src/plugin.cpp#L112).

**Comment by baconpaul** [comment] 2023-01-31 17:33
Thanks @qno

**Comment by qno** [comment] 2023-01-31 18:16
OK - so now I tried to add support for arm64 platform, because - why not.

But I can't test if this works, so replace the `Rack-SDK.cmake` and `Makefile' with the adapted versions from the branch [experimental-linux-arm64-build](https://github.com/qno/vcv-plugin-cmake-example/tree/experimental-linux-arm64-build)
and see what happens.

See changes here - https://github.com/qno/vcv-plugin-cmake-example/pull/4

**Comment by baconpaul** [comment] 2023-01-31 21:43
@jackokring only you can test this I think

but if it works we can propagate it appropriately

**Comment by qno** [comment] 2023-02-01 09:51
OK, I won't fix this problem if the platform is not officially supported by Rack. It is not an easy task and I already wasted too much time on this now for basically nothing. You are on your own here. You better know what you are doing, if not, my advice is just leave it alone.

**Closed as completed by qno** 2023-02-01 09:51 UTC

**Comment by baconpaul** [comment] 2023-02-01 13:08
yeah thanks for the efforts @qno
